"""Recording-related schemas."""

from .config_update import RecordingConfigUpdateRequest
from .filters import RecordingFilters
from .operations import (
    ConfigSaveResponse,
    ConfigUpdateResponse,
    DeleteRecordingResponse,
    DryRunResponse,
    MappingStatusResponse,
    PauseRecordingResponse,
    RecordingBulkDeleteResponse,
    RecordingBulkOperationResponse,
    RecordingConfigResponse,
    RecordingOperationResponse,
    ResetRecordingResponse,
    RestoreRecordingResponse,
    TemplateBindResponse,
    TemplateInfoResponse,
    TemplateUnbindResponse,
)
from .request import (
    AddPlaylistByUrlRequest,
    AddPlaylistResponse,
    AddVideoByUrlRequest,
    AddVideoByUrlResponse,
    AddYandexDiskUrlRequest,
    BulkDeleteRequest,
    BulkDownloadRequest,
    BulkRunRequest,
    BulkSubtitlesRequest,
    BulkTopicsRequest,
    BulkTranscribeRequest,
    BulkTrimRequest,
    BulkUploadRequest,
    ConfigOverrideRequest,
    TrimVideoRequest,
)
from .response import (
    DetailedRecordingResponse,
    RecordingListItem,
    RecordingListResponse,
    RecordingResponse,
)

__all__ = [
    "AddPlaylistByUrlRequest",
    "AddPlaylistResponse",
    "AddVideoByUrlRequest",
    "AddVideoByUrlResponse",
    "AddYandexDiskUrlRequest",
    "BulkDeleteRequest",
    "BulkDownloadRequest",
    "BulkRunRequest",
    "BulkSubtitlesRequest",
    "BulkTopicsRequest",
    "BulkTranscribeRequest",
    "BulkTrimRequest",
    "BulkUploadRequest",
    "ConfigOverrideRequest",
    "ConfigSaveResponse",
    "ConfigUpdateResponse",
    "DeleteRecordingResponse",
    "DetailedRecordingResponse",
    "DryRunResponse",
    "MappingStatusResponse",
    "PauseRecordingResponse",
    "RecordingBulkDeleteResponse",
    "RecordingBulkOperationResponse",
    "RecordingConfigResponse",
    "RecordingConfigUpdateRequest",
    "RecordingFilters",
    "RecordingListItem",
    "RecordingListResponse",
    "RecordingOperationResponse",
    "RecordingResponse",
    "ResetRecordingResponse",
    "RestoreRecordingResponse",
    "TemplateBindResponse",
    "TemplateInfoResponse",
    "TemplateUnbindResponse",
    "TrimVideoRequest",
]
